"""Exercise the dynamic boiler through a real HA platform and service registry."""

from datetime import timedelta

from homeassistant.util import dt as dt_util
from pytest_homeassistant_custom_component.common import (
    MockConfigEntry,
    async_fire_time_changed,
)

from custom_components.virtual_layer import get_entity_from_domain
from tests.unit.test_boiler_control import config, source


async def test_dynamic_boiler_setup_service_timer_reload_and_unload(
    hass, tmp_path, monkeypatch
):
    monkeypatch.setattr(
        "custom_components.virtual_layer.cfg.default_meta_file",
        lambda _: str(tmp_path / "meta.json"),
    )
    source(hass)
    hass.states.async_set("sensor.room_a", "20", {"unit_of_measurement": "°C"})
    hass.states.async_set("sensor.room_b", "22", {"unit_of_measurement": "°C"})
    stored = {**config(), "platform": "climate", "persistent": True}
    # Runtime identity fields are generated by the integration.
    for key in ("unique_id", "device_id"):
        stored.pop(key, None)
    entry = MockConfigEntry(
        domain="virtual_layer",
        data={"group_name": "dynamic"},
        options={"devices": {"Boiler": [stored]}},
    )
    entry.add_to_hass(hass)
    assert await hass.config_entries.async_setup(entry.entry_id)
    await hass.async_block_till_done()
    boiler = get_entity_from_domain(hass, "climate", "climate.virtual_boiler")
    assert boiler is not None
    assert hass.states.get(boiler.entity_id).attributes["temperature"] is None
    await hass.services.async_call(
        "climate",
        "set_temperature",
        {
            "entity_id": boiler.entity_id,
            "temperature": 26,
        },
        blocking=True,
    )
    assert hass.states.get(boiler.entity_id).attributes["temperature"] == 26
    calls = []
    hass.services.async_register(
        "climate", "set_temperature", lambda call: calls.append(call)
    )
    now = dt_util.utcnow()
    async_fire_time_changed(hass, now + timedelta(seconds=61))
    await hass.async_block_till_done()
    assert len(calls) == 1
    assert calls[0].data["temperature"] == 42
    assert await hass.config_entries.async_reload(entry.entry_id)
    await hass.async_block_till_done()
    restored = get_entity_from_domain(hass, "climate", "climate.virtual_boiler")
    assert restored is not boiler
    assert boiler._boiler_stopping
    assert restored.target_temperature == 26
    assert await hass.config_entries.async_unload(entry.entry_id)
    await hass.async_block_till_done()
    async_fire_time_changed(hass, now + timedelta(minutes=10))
    await hass.async_block_till_done()
    assert len(calls) == 1
